// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team5114.MyRobot2016.auton.modes;

import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc.team5114.MyRobot2016.Robot;
import org.usfirst.frc.team5114.MyRobot2016.auton.commands.*;
import org.usfirst.frc.team5114.MyRobot2016.subsystems.*;

/**
 *
 */
public class LowBar extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public LowBar()
    {
    	super("Low Bar");
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
    	
    	System.out.println("---------------Auton Mode: LOW BAR-----------------");
    	//set back to 0.5
    	addSequential(new DropGateArmAutonCmd(0.5, 1.5));
    	
    	addSequential(new DriveNorthAutonCmd(0.5, 2.0));
    	
    	addSequential(new LiftGateArmAutonCmd(0.5, 1.5));
    	
//    	addSequential(new HalfDriveAutonCmd(0.5, 0.5, DriveTrain.Side.right));
//    	addSequential(new HalfDriveAutonCmd(-0.5, 0.5, DriveTrain.Side.left));
    }
}
