// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team5114.MyRobot2016.auton.modes;

import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc.team5114.MyRobot2016.auton.commands.DriveNorthAutonCmd;
import org.usfirst.frc.team5114.MyRobot2016.auton.commands.DriveSouthAutonCmd;
import org.usfirst.frc.team5114.MyRobot2016.subsystems.*;

/**
 *
 */
public class Ramparts extends CommandGroup {

    public Ramparts()
    {
    	super("Ramparts");
    	
    	addSequential(new DriveSouthAutonCmd(0.6, 2.5));
    }
}
