// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team5114.MyRobot2016;

import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.BuiltInAccelerometer;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.interfaces.Accelerometer;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.Relay.Direction;
import edu.wpi.first.wpilibj.Relay.Value;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.SpeedController;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainTalon1;
    public static CANTalon driveTrainTalon2;
    public static CANTalon driveTrainTalon3;
    public static CANTalon driveTrainTalon4;
    
    public static CANTalon ballLaunchTalon5;
    
    public static CANTalon robotLiftTalon6;
    public static CANTalon robotLiftTalon9;
    //public static Servo ...liftyThing...Servo1
    //public static Servo ...liftyThing...Servo2
    
    //public static VictorSP rightArmVictor1;
    
    public static VictorSP ballIntakeVictor7;
    
    public static CANTalon gateKeeperTalon8;
    
    public static Relay lightRelay;
    
    public static UltrasonicAnalog ultraSensor;
    public static Accelerometer accel;
    
    public static AnalogGyro gyro;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainTalon1 = new CANTalon(1);
        LiveWindow.addActuator("Drive Train", "Talon 1", driveTrainTalon1);
        
        driveTrainTalon2 = new CANTalon(2);
        LiveWindow.addActuator("Drive Train", "Talon 2", driveTrainTalon2);
        
        driveTrainTalon3 = new CANTalon(3);
        LiveWindow.addActuator("Drive Train", "Talon 3", driveTrainTalon3);
        
        driveTrainTalon4 = new CANTalon(4);
        LiveWindow.addActuator("Drive Train", "Talon 4", driveTrainTalon4);
        
        ballLaunchTalon5 = new CANTalon(5);
        LiveWindow.addActuator("Ball Launch", "Talon 5", ballLaunchTalon5);
        
        robotLiftTalon6 = new CANTalon(6);
        LiveWindow.addActuator("Robot Lift", "Winch Talon 6", robotLiftTalon6);
        
        robotLiftTalon9 = new CANTalon(9);
        LiveWindow.addActuator("Robot Lift", "Hook Talon 9", robotLiftTalon6);
        
        ballIntakeVictor7 = new VictorSP(0);
        LiveWindow.addActuator("Ball Intake", "VictorSP 0", (VictorSP) ballIntakeVictor7);
        
//        rightArmVictor1 = new VictorSP(1);
//        LiveWindow.addActuator("Right Arm", "VictorSP 1", (VictorSP) rightArmVictor1);
        
        gateKeeperTalon8 = new CANTalon(8);
        LiveWindow.addActuator("Gate Keeper", "Talon 8", gateKeeperTalon8);
        
        ultraSensor = new UltrasonicAnalog(1);
        LiveWindow.addSensor("Ultrasonic Analog", 1, ultraSensor);
        
        gyro = new AnalogGyro(0);
        
        //lightRelay = new Relay(0, Direction.kForward);
        //LiveWindow.addActuator("Shooter Relay", 2, lightRelay);

        double voltsPerDegreePerSecond =0.007;
        gyro.setSensitivity(voltsPerDegreePerSecond);
        
      gyro.initGyro();
      gyro.calibrate();
      gyro.setSensitivity(voltsPerDegreePerSecond);
      
      gyro.reset();
      gyro.setSensitivity(voltsPerDegreePerSecond);
        LiveWindow.addSensor("Analog Gyro", 0, gyro);
        
        accel = new BuiltInAccelerometer();
//      accel.setRange(range);
        //LiveWindow.addSensor("Accelerometer", 0, accel);
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
